import { Navbar } from "../components/Navbar";
import { Card } from "../components/Card";

const lastUpdated = "June 21, 2026";

export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen bg-background text-text-primary selection:bg-primary-blue/30 font-sans">
      <Navbar />
      <main className="container mx-auto px-4 py-16 max-w-3xl">
        <h1 className="font-display text-3xl sm:text-4xl font-semibold mb-2">Terms of Service</h1>
        <p className="text-sm text-text-secondary mb-10">Last updated: {lastUpdated}</p>

        <Card className="p-6 sm:p-8 space-y-8 leading-relaxed text-sm sm:text-base text-text-secondary">
          <section>
            <h2 className="font-display text-xl font-semibold text-text-primary mb-3">1. Agreement to terms</h2>
            <p>
              These Terms of Service ("Terms") govern your use of SkillSync AI ("SkillSync", "we", "us"). By creating
              an account or using the service, you agree to these Terms. If you don't agree, please don't use
              SkillSync.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl font-semibold text-text-primary mb-3">2. Who can use SkillSync</h2>
            <p>
              You must be at least 13 years old to use SkillSync. By using the service, you represent that you meet
              this requirement and that the information you provide is accurate.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl font-semibold text-text-primary mb-3">3. Your account</h2>
            <p>
              You're responsible for keeping your account credentials secure and for all activity that happens under
              your account. Let us know right away if you suspect unauthorized access.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl font-semibold text-text-primary mb-3">4. What SkillSync does</h2>
            <p className="mb-3">
              SkillSync provides AI-assisted career tools, including resume parsing, skill-gap analysis, job market
              trend data ("Radar"), career roadmaps, mock interview practice, and an AI chat assistant. Outputs are
              generated using third-party AI models (OpenAI, Google Gemini) and live job-market data sources.
            </p>
            <p>
              <strong className="text-text-primary">AI-generated content may be inaccurate.</strong> Skill assessments, salary estimates, job-market
              trends, roadmaps, and chatbot responses are generated by AI and automated data sources. They are
              provided for informational purposes only and should not be treated as professional, legal, financial,
              or career advice. Always use your own judgment, and verify important information (e.g. salary figures,
              job requirements) independently before acting on it.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl font-semibold text-text-primary mb-3">5. Acceptable use</h2>
            <p className="mb-3">You agree not to:</p>
            <ul className="list-disc pl-5 space-y-1.5">
              <li>Use the service for any unlawful purpose or to violate any applicable law or regulation.</li>
              <li>Upload content that infringes someone else's intellectual property or privacy rights.</li>
              <li>Attempt to reverse-engineer, scrape, or abuse the service or its rate limits.</li>
              <li>Use automated means (bots, scripts) to access the service outside of normal use.</li>
              <li>Misrepresent your identity or impersonate another person.</li>
            </ul>
          </section>

          <section>
            <h2 className="font-display text-xl font-semibold text-text-primary mb-3">6. Your content</h2>
            <p>
              You retain ownership of the resumes, text, and other content you submit to SkillSync ("Your Content").
              By submitting it, you grant us a limited license to process it (including sending it to the third-party
              AI providers and data sources described in our Privacy Policy) solely to provide the features you
              request. We don't use Your Content to train our own AI models, and we don't sell it.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl font-semibold text-text-primary mb-3">7. Usage limits and availability</h2>
            <p>
              Some features have usage limits (e.g. a maximum number of saved analyses) that may change over time.
              We aim to keep SkillSync available and reliable, but we don't guarantee uninterrupted access — the
              service may be unavailable at times for maintenance, updates, or due to factors outside our control
              (including outages of third-party providers we depend on).
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl font-semibold text-text-primary mb-3">8. Intellectual property</h2>
            <p>
              SkillSync's branding, design, and underlying software are owned by us or our licensors and protected by
              applicable intellectual property laws. These Terms don't grant you any rights to our trademarks, logos,
              or branding.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl font-semibold text-text-primary mb-3">9. Termination</h2>
            <p>
              You may stop using SkillSync and request account deletion at any time. We may suspend or terminate your
              access if you violate these Terms, misuse the service, or for security or legal reasons, with notice
              where reasonably possible.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl font-semibold text-text-primary mb-3">10. Disclaimers</h2>
            <p>
              SkillSync is provided "as is" and "as available," without warranties of any kind, express or implied,
              including warranties of merchantability, fitness for a particular purpose, or non-infringement. We
              don't warrant that AI-generated outputs will be accurate, complete, or suitable for your specific
              situation.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl font-semibold text-text-primary mb-3">11. Limitation of liability</h2>
            <p>
              To the fullest extent permitted by law, SkillSync and its team will not be liable for any indirect,
              incidental, special, consequential, or punitive damages, or any loss of profits, data, or career
              opportunities, arising from your use of (or inability to use) the service, including reliance on
              AI-generated content.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl font-semibold text-text-primary mb-3">12. Changes to these terms</h2>
            <p>
              We may update these Terms from time to time. If we make material changes, we'll update the "Last
              updated" date above and, where appropriate, notify you in-app. Continued use of SkillSync after changes
              take effect means you accept the updated Terms.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl font-semibold text-text-primary mb-3">13. Contact us</h2>
            <p>
              Questions about these Terms? Email us at{" "}
              <a href="mailto:projectsa241@gmail.com" className="text-primary-blue hover:underline">
                projectsa241@gmail.com
              </a>.
            </p>
          </section>
        </Card>
      </main>
    </div>
  );
}
